name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' 
        java-package: 'jdk'

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install required Python packages
      run: pip install smtplib
      
    - name: Build with Maven
      run: mvn clean package --batch-mode

    - name: Send notification on success
      if: success()
      run: python3 PipeLineProject/send_email.py "Build Success" "The build succeeded!"
      env:
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASS: ${{ secrets.SMTP_PASS }}

    - name: Send notification on failure
      if: failure()
      run: python3 PipeLineProject/send_email.py "Build Failure" "The build failed. Please check the logs for more details."
      env:
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASS: ${{ secrets.SMTP_PASS }}
      
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        java-package: 'jdk'
        
    - name: Run tests
      run: mvn test --batch-mode

    - name: Package the application
      run: mvn package --batch-mode

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: target/surefire-reports/ # Path to Maven Surefire test reports
