name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package

    - name: Archive JAR file
      uses: actions/upload-artifact@v3
      with:
        name: sampleapp
        path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download JAR file
      uses: actions/download-artifact@v3
      with:
        name: sampleapp

    - name: Deploy to Server
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      run: |
        scp -o StrictHostKeyChecking=no target/*.jar $SERVER_USER@$SERVER_HOST:/path/to/deploy
        ssh $SERVER_USER@$SERVER_HOST << 'EOF'
        # Commands to start the application on your server
        java -jar /path/to/deploy/sampleapp.jar &
        EOF
